export const TABLET_SCREEN_WIDTH = 768;
export const DESKTOP_SCREEN_WIDTH = 1024;
export const MOBILE_SCREEN_WIDTH = 600;
export const USE_DEFAULT_GENERATED_TEXT = "USE_DEFAULT_GENERATED_TEXT";
export const USE_USER_GENERATED_TEXT = "USE_USER_GENERATED_TEXT";