import type { GetStaticProps, NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head' 

const DynamicTestBlock = dynamic(
  () => import('../components/TestBlock'),
  { ssr: false }
)

const Home: NextPage = () => {
  
  return (
    <div>
      <Head>
        <title>Swift Hands</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  
      <DynamicTestBlock />
    </div>
  )
}
 
export default Home
